[package]
name = "unchainedcoin"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
blake3 = "1.5"
argon2 = "0.5"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
pqcrypto-dilithium = "0.5.0"
pqcrypto-traits = "0.3"
libp2p = { version = "0.53", features = ["quic", "tokio", "gossipsub", "mdns", "macros"] }
rocksdb = "0.21"
prometheus = "0.13"
futures = "0.3"
anyhow = "1.0"
toml = "0.8"
bincode = "1.3"
zstd = "0.13"
hex = "0.4"
tiny_http = "0.12"
serde-big-array = "0.5"

[dev-dependencies]
tempfile = "3.8"
