[package]
name = "unchainedcoin"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
blake3 = "1.5"
argon2 = "0.5"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pqcrypto-dilithium = "0.5.0"
pqcrypto-traits = "0.3"
libp2p = { version = "0.56", features = ["quic", "tcp", "tokio", "mdns", "macros", "identify", "noise", "yamux"] }
libp2p-gossipsub = "0.49"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rocksdb = "0.21"
lz4_flex = "0.11"
prometheus = "0.13"
futures = "0.3"
anyhow = "1.0"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["server"] }
bincode = "2"
toml = "0.8"
