[net]
listen_port = 31111
peer_exchange = false
bootstrap = []
public_ip = "127.0.0.1"
max_peers = 32
connection_timeout_secs = 60
sync_timeout_secs = 5

[p2p]
max_validation_failures_per_peer = 100
peer_ban_duration_secs = 3600
rate_limit_window_secs = 600
max_messages_per_window = 1000

[storage]
path = "/Users/numan/unchained/.test_chain_data"

[epoch]
seconds = 5

[mining]
enabled = false
heartbeat_interval_secs = 5
max_mining_attempts = 1000

[metrics]
bind = "127.0.0.1:9191"
