name: Release (Windows)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and release Windows .exe
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install OpenSSL
        shell: pwsh
        run: choco install openssl --no-progress -y

      - name: Export OpenSSL environment
        shell: pwsh
        run: |
          echo "OPENSSL_ROOT_DIR=C:\\Program Files\\OpenSSL-Win64" >> $env:GITHUB_ENV
          echo "OPENSSL_DIR=C:\\Program Files\\OpenSSL-Win64" >> $env:GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=C:\\Program Files\\OpenSSL-Win64" >> $env:GITHUB_ENV
          echo "Path=$env:Path;C:\\Program Files\\OpenSSL-Win64\\bin" >> $env:GITHUB_ENV

      - name: Cache cargo and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build (release, static CRT)
        run: cargo build --locked --release
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"

      - name: Smoke test executable
        shell: pwsh
        run: |
          & target/release/unchained.exe --version

      - name: Prepare release assets
        shell: pwsh
        run: |
          # Verify binaries exist
          Get-ChildItem -Path target/release -Filter *.exe
          # Staging directory for flattened zip contents
          $dist = "dist/windows"
          if (Test-Path $dist) { Remove-Item $dist -Recurse -Force }
          New-Item -ItemType Directory -Path $dist | Out-Null
          # Copy artifacts into staging dir (flattened)
          Copy-Item -Path target/release/unchained.exe -Destination "$dist/unchained.exe" -Force
          Copy-Item -Path target/release/inspect_db.exe -Destination "$dist/inspect_db.exe" -Force
          Copy-Item -Path config.toml -Destination "$dist/config.toml" -Force
          Copy-Item -Path README.md -Destination "$dist/README.md" -Force
          Copy-Item -Path unchained-run.bat -Destination "$dist/unchained-run.bat" -Force
          # Bundle a zip with exe + config + README + launcher (flattened)
          $zipPath = "target/release/unchained-windows-x86_64.zip"
          if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
          Compress-Archive -Path "$dist/*" -DestinationPath $zipPath

      - name: Compute release metadata
        id: meta
        shell: pwsh
        run: |
          $short = $env:GITHUB_SHA.Substring(0,7)
          "tag=auto-main-$short" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "name=Main build $short" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Create Release and Upload Assets (.exe)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.name }}
          target_commitish: ${{ github.sha }}
          files: |
            target/release/unchained.exe
            target/release/inspect_db.exe
            target/release/unchained-windows-x86_64.zip
            unchained-run.bat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


